[package]
name = "data_structures_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "avl"
path = "./avl_tree/tree/lib.rs"

[[test]]
name = "avl_unit"
path = "./avl_tree/tests.rs"